SUPABASE_URL = "https://qunsuzykvywvrvosvznl.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF1bnN1enlrdnl3dnJ2b3N2em5sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQzMTQ5MjAsImV4cCI6MjA3OTg5MDkyMH0.sLGHhTgRYbbbCcJAdeaKMHRzMbq7IrjI85tBzxAYxWQ"
ROOM_CAPACITY = "999"